### ISSUE TITLE
Unclear relation betwen padded r2c / c2r and in-place transform.

### ISSUE THREAD

**Issue by rainwoodman** [mpip/pfft#15]
The documentation seems to suggest it is possible to do in-place r2c/c2r without PFFT_PADDED_R2C.
I don't think it's possible, or is it?

**Comment by mpip** [comment]
It is possible to compute r2c/c2r PFFT in-place without padding. Internally, the real valued arrays are remapped to the correct strides (including padding) before the in-place FFTW is applied.
This remap can be combined with pruning, so the user does not have a performance penalty if pruning and non-padded r2c PFFT is computed in-place. 


If pruned PFFT is used this remapping

**Comment by rainwoodman** [comment]
Thanks for the clarification. You mean, with the current version of PFFT, r2c /c2r without PFFT_PADDED_R2C is correctly implemented; but a bit slower than padded transform?

**Comment by mpip** [comment]
Correct. However, if you use pruned input arrays that will be filled 
with zeros before FFT, then, you will not see a performance penalty.

Am 05.09.2015 um 22:35 schrieb Yu Feng:
>
> Thanks for the clarification. You mean, with the current version of 
> PFFT, r2c /c2r without PFFT_PADDED_R2C is correctly implemented; but a 
> bit slower than padded transform?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mpip/pfft/issues/15#issuecomment-137993395>.
>


-- 
**********************************************************
Michael Pippig
Technische Universität Chemnitz
Faculty of Mathematics
Reichenhainer Str. 39
09126 Chemnitz
Germany

Phone: +49-371-531-37833
Fax:   +49-371-531-837833
eMail: michael.pippig.tuc@gmail.com
WWW:   http://www.tu-chemnitz.de/~mpip
**********************************************************
