### ISSUE TITLE
Fortran interface to pfft_plan_with_nthreads missing

### ISSUE THREAD

**Issue by LadaF** [mpip/pfft#21]
The Fortran interface to  pfft_plan_with_nthreads is missing. I use this:

      interface
        subroutine pfft_plan_with_nthreads(nthreads) bind(C, name="pfft_plan_with_nthreads")
          import
          integer(C_INT), value :: nthreads
        end subroutine
      end interface

**Comment by mpip** [comment]
Thanks for the report. I forgot to update the Fortran interface after the last merge. Note that the Fortran 2003 interface can be automatically generated using
  `./f03-api.sh d f > pfft.f03.in`
  `./f03-api.sh l > pfftl.f03.in`
within the api directory. I pushed the updated Fortran 2003 interface to master.
