### ISSUE TITLE
Large errors in single precision roundtrips.

### ISSUE THREAD

**Issue by rainwoodman** [mpip/pfft#8]
With a 16x16x16 mesh and dividing to 4 processes (1x4, 4x1, 2x2),  
the roundtrip error on a gaussian initial field (r->c c->r) can be as big as 0.001.

The error is also large even on 1 process (comparing with numpy.fft), typically around 2e-5 in forward, and cummulates to ~ 0.002 after backward.

I wonder how this compares with FFTWF. And is there anything we can do about it.

**Comment by mpip** [comment]
Thanks for the report. Can you create a minimal example to reproduce the behavior? 
I assume that you already considered the right rescaling with the FFT size after one roundtrip. I don't think that FFTWF will do it better. It's more likely, that something is going wrong with the parallel decomposition.

**Comment by rainwoodman** [comment]
Turns out my test on the round trip was looking at the error multipled by product(Nmesh). The error was actually small. Nothing wrong with the parallel decomposition as far as this issue is concerned. 

I am closing it. Thanks.
